name: newsify
description: "A new Flutter project for Final Project App Sanber Bootcamp."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.7.2
  image_picker: ^1.1.2

  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  http: ^1.3.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
